[package]
name = "bls_test"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = { version = "0.13", features = ["arithmetic"] }
p521 = { version = "0.13", features = ["arithmetic"] }
rand = "0.8"
rand_core = "0.6"
elliptic-curve = "0.13"
